[General]
showlogo=shown
showClock=true
logo=/usr/share/sddm/themes/UnnoyonOS/default-logo.svg
type=image
color=#2E7D32
fontSize=10
background=/usr/share/wallpapers/unnoyonos-dark-signature/contents/images/1376x768.png
needsFullUserModel=false
